name: game_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.1
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  pedantic: ^1.11.1
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
